Models/Confederacao.cs
namespace TwoFootball.Models;
using System.ComponentModel.DataAnnotations;


public class Confederacao
{
    public int? Id { get; set; }

    [Required(ErrorMessage = "Preencha o campo Nome")]
    [StringLength(50, ErrorMessage = "O campo Nome pode ter no máximo 50 caracteres")]
    public String? Nome { get; set; }

    [Required(ErrorMessage = "Preencha o campo Continente")]
    [StringLength(50, ErrorMessage = "O campo Continente pode ter no máximo 50 caracteres")]
    public String? Continente { get; set; }

    [Required(ErrorMessage = "Preencha o campo Vagas")]
    [Range(0, 13, ErrorMessage = "O campo Vagas necessita estar no intervalo de 0 a 13")]
    public int? Vagas { get; set; }

    public Confederacao()
    {
        
    }

    public Confederacao(int id, String nome, string continente, int vagas)
    {
        Id = id;
        Nome = nome;
        Vagas = vagas;
    }
}

Controllers/ConfederacaoController.cs
using Microsoft.AspNetCore.Mvc;
using TwoFootball.Models;

namespace TwoFootball.Controllers;

public class ConfederacaoController : Controller 
{
    private readonly TwoFootballContext _context;

    public ConfederacaoController(TwoFootballContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        return View(_context.Confederacao);
    }

    public IActionResult Show(int id)
    {
        Confederacao confederacao = _context.Confederacao.Find(id);

        if(confederacao == null)
        {
            return NotFound();
        }

        return View(confederacao);
    }

    [HttpGet]
    public IActionResult Cadastrar()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Cadastrar(Confederacao confederacao)
    {
        if(!ModelState.IsValid) 
        {
            return View(confederacao);
        }

        _context.Confederacao.Add(confederacao);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Update(int id)
    {
        Confederacao confederacao = _context.Confederacao.Find(id);

        if(confederacao == null)
        {
            return NotFound();
        }

        return View(confederacao);
    }

    [HttpPost]
    public IActionResult Update(Confederacao confederacao, int id)
    {
        if(!ModelState.IsValid) 
        {
            return View(confederacao);
        }
        
        Confederacao updateConfederacao = _context.Confederacao.Find(confederacao.Id);
        
        updateConfederacao.Nome = confederacao.Nome;
        updateConfederacao.Continente = confederacao.Continente;
        updateConfederacao.Vagas = confederacao.Vagas;

        _context.Confederacao.Update(updateConfederacao);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        Confederacao confederacao = _context.Confederacao.Find(id);

        if(confederacao == null)
        {
            return NotFound();
        }
        
        _context.Confederacao.Remove(_context.Confederacao.Find(id));
        _context.SaveChanges();

        return RedirectToAction("Index");
    }


}

Views/Confederacao/Cadastrar.cshtml
@model TwoFootball.Models.Confederacao

@{
    ViewData["Title"] = "Cadastrar";
}

<form class="form" id="form" asp-controller="Confederacao" asp-action="Cadastrar" method="POST">
    <label for="Nome">Nome: </label>
    <input type="text" id="Nome" name="Nome" asp-for="@Model.Nome">
    <span asp-validation-for="@Model.Nome" class="text-danger"></span>

    <label for="Continente">Continente: </label>
    <input type="text" id="Continente" name="Continente" asp-for="@Model.Continente">
    <span asp-validation-for="@Model.Continente" class="text-danger"></span>

    <label for="Vagas">Vagas: </label>
    <input type="number" id="Vagas" name="Vagas" asp-for="@Model.Vagas">
    <span asp-validation-for="@Model.Vagas" class="text-danger"></span>

    <input type="submit" value="Cadastrar">
</form>

Views/Confederacao/Index.cshtml
@model IEnumerable<TwoFootball.Models.Confederacao>
@{
    ViewData["Title"] = "Confederações";
}
<h1>@ViewData["Title"]</h1>

@if(Model.Count() == 0)
{
    <p>Nenhuma confederação cadastrada</p>
    <a class="btn btn-outline-dark" asp-controller="Confederacao" asp-action="Cadastrar">Cadastre uma nova confederação</a>
}
else
{
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Continente</th>
                <th>Vagas</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var confederacao in Model)
            {
                <tr>
                    <td>@confederacao.Id</td>
                    <td>@confederacao.Nome</td>
                    <td>@confederacao.Continente</td>
                    <td>@confederacao.Vagas</td>
                    <td>
                        <a class="btn btn-outline-info" asp-controller="Confederacao" asp-action="Show" asp-route-id="@confederacao.Id">Ver</a>
                        <a class="btn btn-outline-light" asp-controller="Confederacao" asp-action="Update" asp-route-id="@confederacao.Id">Update</a>
                        <a class="btn btn-outline-danger" asp-controller="Confederacao" asp-action="Delete" asp-route-id="@confederacao.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-outline-dark" asp-controller="Confederacao" asp-action="Cadastrar">Cadastre uma nova confederação</a>
}

Views/Confederacao/Show.cshtml
@model TwoFootball.Models.Confederacao
@{
    ViewData["Title"] = $"Confederação {Model.Id}";
}
<h1>@ViewData["Title"]</h1>

<p><b>Id: </b>@Model.Id</p>
<p><b>Nome: </b>@Model.Nome</p>
<p><b>Continente: </b>@Model.Continente</p>
<p><b>Vagas: </b>@Model.Vagas</p>

Views/Confederacao/Update.cshtml
@model TwoFootball.Models.Confederacao
@{
    ViewData["Title"] = "Atualizar Confederação";
}
<h1>@ViewData["Title"]</h1>

<p>Utilize o formulário para Atualizar a confederação</p>

<form class="form" asp-controller="Confederacao" asp-action="Update" asp-route-id="@Model.Id" method="POST">
    @* Não pode alterar o ID *@
    
    <label for="Nome">Nome</label>
    <input type="text" id="Nome" value="@Model.Nome" name="Nome" asp-for="@Model.Nome">
    <span asp-validation-for="@Model.Nome" class="text-danger"></span>

    <label for="Continente">Continente</label>
    <input type="text" id="Continente" value="@Model.Continente" name="Continente" asp-for="@Model.Continente">
    <span asp-validation-for="@Model.Continente" class="text-danger"></span>

    <label for="Vagas">Vagas</label>
    <input type="number" id="Vagas" value="@Model.Vagas" name="Vagas" asp-for="@Model.Vagas">
    <span asp-validation-for="@Model.Vagas" class="text-danger"></span>

    <input class="submit" type="submit" value="Atualizar">
</form>