Controllers/EstadioController.cs
using Microsoft.AspNetCore.Mvc;
using TwoFootball.Models;

namespace TwoFootball.Controllers;

public class EstadioController : Controller 
{
    private readonly TwoFootballContext _context;

    public EstadioController(TwoFootballContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        return View(_context.Estadio);
    }

    public IActionResult Show(int id)
    {
        Estadio estadio = _context.Estadio.Find(id);

        if(estadio == null)
        {
            return NotFound();
        }

        return View(estadio);
    }

    [HttpGet]
    public IActionResult Cadastrar()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Cadastrar(Estadio estadio)
    {
        if(!ModelState.IsValid) 
        {
            return View(estadio);
        }

        _context.Estadio.Add(estadio);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Update(int id)
    {
        Estadio estadio = _context.Estadio.Find(id);

        if(estadio == null)
        {
            return NotFound();
        }

        return View(estadio);
    }

    [HttpPost]
    public IActionResult Update(Estadio estadio, int id)
    {
        if(!ModelState.IsValid) 
        {
            return View(estadio);
        }

        Estadio updateEstadio = _context.Estadio.Find(estadio.Id);
        
        updateEstadio.Nome = estadio.Nome;
        updateEstadio.Cidade = estadio.Cidade;
        updateEstadio.Capacidade = estadio.Capacidade;


        _context.Estadio.Update(updateEstadio);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        Estadio estadio = _context.Estadio.Find(id);

        if(estadio == null)
        {
            return NotFound();
        }
        
        _context.Estadio.Remove(_context.Estadio.Find(id));
        _context.SaveChanges();

        return RedirectToAction("Index");
    }


}

Controllers/GrupoController.cs
using Microsoft.AspNetCore.Mvc;
using TwoFootball.Models;

namespace TwoFootball.Controllers;

public class GrupoController : Controller 
{
    private readonly TwoFootballContext _context;

    public GrupoController(TwoFootballContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        return View(_context.Grupo);
    }

    public IActionResult Show(int id)
    {
        Grupo grupo = _context.Grupo.Find(id);

        if(grupo == null)
        {
            return NotFound();
        }

        return View(grupo);
    }

    [HttpGet]
    public IActionResult Cadastrar()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Cadastrar(Grupo grupo)
    {
        if(!ModelState.IsValid) 
        {
            return View(grupo);
        }

        _context.Grupo.Add(grupo);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Update(int id)
    {
        
        Grupo grupo = _context.Grupo.Find(id);

        if(grupo == null)
        {
            return NotFound();
        }

        return View(grupo);
    }

    [HttpPost]
    public IActionResult Update(Grupo grupo, int id)
    {
        if(!ModelState.IsValid) 
        {
            return View(grupo);
        }
        
        Grupo updateGrupo = _context.Grupo.Find(grupo.Id);
        
        updateGrupo.Nome = grupo.Nome;
        updateGrupo.Pote1 = grupo.Pote1;
        updateGrupo.Pote2 = grupo.Pote2;
        updateGrupo.Pote3 = grupo.Pote3;
        updateGrupo.Pote4 = grupo.Pote4;

        _context.Grupo.Update(updateGrupo);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        Grupo grupo = _context.Grupo.Find(id);

        if(grupo == null)
        {
            return NotFound();
        }
        
        _context.Grupo.Remove(_context.Grupo.Find(id));
        _context.SaveChanges();

        return RedirectToAction("Index");
    }


}

Controllers/JogadorController.cs
using Microsoft.AspNetCore.Mvc;
using TwoFootball.Models;

namespace TwoFootball.Controllers;

public class JogadorController : Controller 
{
    private readonly TwoFootballContext _context;

    public JogadorController(TwoFootballContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        return View(_context.Jogador);
    }

    public IActionResult Show(int id)
    {
        Jogador jogador = _context.Jogador.Find(id);

        if(jogador == null)
        {
            return NotFound();
        }

        return View(jogador);
    }

    [HttpGet]
    public IActionResult Cadastrar()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Cadastrar(Jogador jogador)
    {
        if(!ModelState.IsValid) 
        {
            return View(jogador);
        }

        _context.Jogador.Add(jogador);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Update(int id)
    {
        Jogador jogador = _context.Jogador.Find(id);

        if(jogador == null)
        {
            return NotFound();
        }

        return View(jogador);
    }

    [HttpPost]
    public IActionResult Update(Jogador jogador, int id)
    {
        if(!ModelState.IsValid) 
        {
            return View(jogador);
        }

        Jogador updateJogador = _context.Jogador.Find(jogador.Id);
        
        updateJogador.Nome = jogador.Nome;
        updateJogador.Posicao = jogador.Posicao;
        updateJogador.Numero = jogador.Numero;
        updateJogador.CopasParticipadas = jogador.CopasParticipadas;
        updateJogador.Nacionalidade = jogador.Nacionalidade;

        _context.Jogador.Update(updateJogador);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        Jogador jogador = _context.Jogador.Find(id);

        if(jogador == null)
        {
            return NotFound();
        }
        
        _context.Jogador.Remove(_context.Jogador.Find(id));
        _context.SaveChanges();

        return RedirectToAction("Index");
    }


}

Controllers/TimeController.cs
using Microsoft.AspNetCore.Mvc;
using TwoFootball.Models;

namespace TwoFootball.Controllers;

public class TimeController : Controller
{
    private readonly TwoFootballContext _context;

    public TimeController(TwoFootballContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Time);
    }

    public IActionResult Show(int id)
    {
        Time time = _context.Time.Find(id);

        if(time == null)
        {
            return NotFound();
        }

        return View(time);
    }

    [HttpGet]
    public IActionResult Cadastrar()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Cadastrar(Time time)
    {
        if(!ModelState.IsValid) 
        {
            return View(time);
        }

        _context.Time.Add(time);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Update(int id)
    {
        Time time = _context.Time.Find(id);

        if(time == null)
        {
            return NotFound();
        }

        return View(time);
    }

    [HttpPost]
    public IActionResult Update(Time time, int id)
    {
        if(!ModelState.IsValid) 
        {
            return View(time);
        }

        Time updateTime = _context.Time.Find(time.Id);
        
        updateTime.Pais = time.Pais;
        updateTime.Patrocinador = time.Patrocinador;
        updateTime.Titulos = time.Titulos;
        updateTime.JogadorDeDestaque = time.JogadorDeDestaque;

        _context.Time.Update(updateTime);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        Time time = _context.Time.Find(id);

        if(time == null)
        {
            return NotFound();
        }
        
        _context.Time.Remove(_context.Time.Find(id));
        _context.SaveChanges();

        return RedirectToAction("Index");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TwoFootball</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TwoFootball.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TwoFootball</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Partida" asp-action="Index">Partidas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Time" asp-action="Index">Times</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Confederacao" asp-action="Index">Confederações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Grupo" asp-action="Index">Grupos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jogador" asp-action="Index">Jogadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estadio" asp-action="Index">Estádios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TwoFootball - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>