Models/Partida.cs
namespace TwoFootball.Models;
using System.ComponentModel.DataAnnotations;


public class Partida{
    public int? Id { get; set; }

    [Required(ErrorMessage = "Preencha o campo Time da Casa")]
    [StringLength(50, ErrorMessage = "O campo Time da Casa pode ter no máximo 50 caracteres")]
    public String? TimeDaCasa { get; set; }

    [Required(ErrorMessage = "Preencha o campo Time Visitante")]
    [StringLength(50, ErrorMessage = "O campo Time Visitante pode ter no máximo 50 caracteres")]
    public String? TimeVisitante { get; set; }

    [Required(ErrorMessage = "Preencha o campo Data")]
    public DateTime? Data { get; set; }
    public Partida() 
    {

    }

    public Partida(int id, String timeDaCasa, String timeVisitante, DateTime data)
    {
        Id = id;
        TimeDaCasa = timeDaCasa;
        TimeVisitante = timeVisitante;
        Data = data;
    }
}

Controllers/PartidaController.cs
using Microsoft.AspNetCore.Mvc;
using TwoFootball.Models;

namespace TwoFootball.Controllers;

public class PartidaController : Controller
{
    private readonly TwoFootballContext _context;

    public PartidaController(TwoFootballContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Partida);
    }

    public IActionResult Show(int id)
    {
        Partida partida = _context.Partida.Find(id);

        if(partida == null)
        {
            return NotFound();
        }

        return View(partida);
    }

    [HttpGet]
    public IActionResult Cadastrar()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Cadastrar(Partida partida)
    {
        if(!ModelState.IsValid) 
        {
            return View(partida);
        }

        _context.Partida.Add(partida);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Update(int id)
    {
        Partida partida = _context.Partida.Find(id);

        if(partida == null)
        {
            return NotFound();
        }

        return View(partida);
    }

    [HttpPost]
    public IActionResult Update(Partida partida, int id)
    {
        if(!ModelState.IsValid) 
        {
            return View(partida);
        }

        Partida updatePartida = _context.Partida.Find(partida.Id);
        
        updatePartida.TimeDaCasa = partida.TimeDaCasa;
        updatePartida.TimeVisitante = partida.TimeVisitante;
        updatePartida.Data = partida.Data;

        _context.Partida.Update(updatePartida);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        Partida partida = _context.Partida.Find(id);

        if(partida == null)
        {
            return NotFound();
        }
        
        _context.Partida.Remove(_context.Partida.Find(id));
        _context.SaveChanges();

        return RedirectToAction("Index");
    }
}

Views/Partida/Cadastrar.cshtml
@model TwoFootball.Models.Partida

@{
    ViewData["Title"] = "Cadastrar";
}

<form class="form" id="form" asp-controller="Partida" asp-action="Cadastrar" method="POST">
    <label for="TimeDaCasa">Time da Casa: </label>
    <input type="text" id="TimeDaCasa" name="TimeDaCasa" asp-for="@Model.TimeDaCasa">
    <span asp-validation-for="@Model.TimeDaCasa" class="text-danger"></span>

    <label for="TimeVisitante">Time Visitante: </label>
    <input type="text" id="TimeVisitante" name="TimeVisitante" asp-for="@Model.TimeVisitante">
    <span asp-validation-for="@Model.TimeVisitante" class="text-danger"></span>

    <label for="Data">Data: </label>
    <input type="datetime-local" id="Data" name="Data" asp-for="@Model.Data">
    <span asp-validation-for="@Model.Data" class="text-danger"></span>

    <input type="submit" value="Cadastrar">
</form>

Views/Partida/Index.cshtml
@model IEnumerable<TwoFootball.Models.Partida>
@{
    ViewData["Title"] = "Partidas";
}
<h1>@ViewData["Title"]</h1>

@if(Model.Count() == 0)
{
    <p>Nenhuma partida cadastrada</p>
    <a class="btn btn-outline-dark" asp-controller="Partida" asp-action="Cadastrar">Cadastre uma nova partida</a>
}
else
{
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Id</th>
                <th>Time Da Casa</th>
                <th>Time Visitante</th>
                <th>Data</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var partida in Model)
            {
                <tr>
                    <td>@partida.Id</td>
                    <td>@partida.TimeDaCasa</td>
                    <td>@partida.TimeVisitante</td>
                    <td>@partida.Data</td>
                    <td>
                        <a class="btn btn-outline-info" asp-controller="Partida" asp-action="Show" asp-route-id="@partida.Id">Ver</a>
                        <a class="btn btn-outline-light" asp-controller="Partida" asp-action="Update" asp-route-id="@partida.Id">Update</a>
                        <a class="btn btn-outline-danger" asp-controller="Partida" asp-action="Delete" asp-route-id="@partida.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-outline-dark" asp-controller="Partida" asp-action="Cadastrar">Cadastre uma nova partida</a>
}

Views/Partida/Show.cshtml
@model TwoFootball.Models.Partida
@{
    ViewData["Title"] = $"Partida do time mandante: {Model.TimeDaCasa}";
}
<h1>@ViewData["Title"]</h1>

<p><b>Id: </b>@Model.Id</p>
<p><b>Time da Casa: </b>@Model.TimeDaCasa</p>
<p><b>Time Visitante: </b>@Model.TimeVisitante</p>
<p><b>Data: </b>@Model.Data</p>

Views/Partida/Update.cshtml
@model TwoFootball.Models.Partida
@{
    ViewData["Title"] = "Atualizar Partida";
}
<h1>@ViewData["Title"]</h1>

<p>Utilize o formulário para Atualizar a partida</p>

<form class="form" asp-controller="Partida" asp-action="Update" asp-route-id="@Model.Id" method="POST">
    @* Não pode alterar o ID *@
    
    <label for="TimeDaCasa">Time da Casa: </label>
    <input type="text" id="TimeDaCasa" name="TimeDaCasa" value="@Model.TimeDaCasa" asp-for="@Model.TimeDaCasa">
    <span asp-validation-for="@Model.TimeDaCasa" class="text-danger"></span>

    <label for="TimeVisitante">Time Visitante: </label>
    <input type="text" id="TimeVisitante" name="TimeVisitante" value="@Model.TimeVisitante" asp-for="@Model.TimeVisitante">
    <span asp-validation-for="@Model.TimeVisitante" class="text-danger"></span>

    <label for="Data">Data: </label>
    <input type="datetime-local" id="Data" name="Data" value="@Model.Data" asp-for="@Model.Data">
    <span asp-validation-for="@Model.Data" class="text-danger"></span>

    <input type="submit" value="Atualizar">
</form>